---
apiVersion: v1
kind: Namespace
metadata:
  name: core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-namespace
  namespace: flux-system
spec:
  interval: 1m
  resources:
    - ./clusters/home/core-namespace.yaml  # file containing Namespace manifest above
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: core-namespace
  path: "./clusters/home/core"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
