apiVersion: v1
kind: Namespace
metadata:
  name: radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: radarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
  - host: radarr.kube.tuntelder.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878
  tls:
  - hosts:
    - radarr.kube.tuntelder.com
