apiVersion: v1
kind: Namespace
metadata:
  name: sonarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: tv-shows
          mountPath: /tv
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  namespace: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
