apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  namespace: sonarr
spec:
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: sonarr
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
  - host: sonarr.kube.tuntelder.com   # <-- Your domain here
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr-lb
            port:
              number: 8989
  tls:
  - hosts:
    - sonarr.kube.tuntelder.com
