apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: traefik
    envs:
      - .env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - roles.yaml
  