apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-access
rules:
- apiGroups: [""]
  resources: ["secrets", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io", "extensions"]
  resources: ["ingresses","ingressclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-secret-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-secret-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: traefik
